INSERT INTO TEAM (NAME) VALUES ('Kubbisten');
INSERT INTO TEAM (NAME) VALUES ('Vlaanderen Kubbt');
INSERT INTO TEAM (NAME) VALUES ('El Kubbidos Del Mundo');
INSERT INTO TEAM (NAME) VALUES ('De Dissers');
INSERT INTO TEAM (NAME) VALUES ('OHC');